### ISSUE TITLE
build fails 

### ISSUE THREAD

**Issue by dsnezhkov** [eagleas/clamav#2]
Hi, 

I have:
ubuntu 9.10
ruby 1.9.0 (2008-10-04 revision 19669) [i486-linux]

and the gem build is failing:

 sudo gem install warp-clamav
Building native extensions.  This could take a while...
ERROR:  Error installing warp-clamav:
        ERROR: Failed to build gem native extension.

/usr/bin/ruby1.9 extconf.rb
checking for clamav.h... yes
checking for cl_engine_compile() in -lclamav... yes
creating Makefile

make
gcc -I. -I/usr/include/ruby-1.9.0/i486-linux -I/usr/include/ruby-1.9.0/ruby/backward -I/usr/include/ruby-1.9.0 -I. -DHAVE_CLAMAV_H  -D_FILE_OFFSET_BITS=64  -fPIC -fno-strict-aliasing -g -g -O2 -O2 -g -Wall -Wno-parentheses  -fPIC  -o clamav.o -c clamav.c
clamav.c: In function âclamavr_newâ:
clamav.c:28: warning: unused variable âv_fnameâ
clamav.c: In function âclamavr_setstringâ:
clamav.c:116: error: âstruct RStringâ has no member named âptrâ
clamav.c: In function âclamavr_scanfileâ:
clamav.c:166: error: âstruct RStringâ has no member named âptrâ
make: **\* [clamav.o] Error 1

Gem files will remain installed in /var/lib/gems/1.9.0/gems/warp-clamav-0.3.1 for inspection.
Results logged to /var/lib/gems/1.9.0/gems/warp-clamav-0.3.1/ext/clamav/gem_make.out

thanks.

**Comment by eagleas** [comment]
See commit http://github.com/eagleas/clamav/commit/79731912704aaf75ddf8ac347d98daab284c71c3

**Comment by eagleas** [comment]
Please, use "official" http://github.com/eagleas/clamav, not warp-clamav.

**Comment by dsnezhkov** [comment]
Yes, I tried it first, same issue:

 cat /var/lib/gems/1.9.0/gems/clamav-0.3.1/ext/clamav/gem_make.out
/usr/bin/ruby1.9 extconf.rb
checking for clamav.h... yes
checking for cl_engine_compile() in -lclamav... yes
creating Makefile

make
gcc -I. -I/usr/include/ruby-1.9.0/i486-linux -I/usr/include/ruby-1.9.0/ruby/backward -I/usr/include/ruby-1.9.0 -I. -DHAVE_CLAMAV_H  -D_FILE_OFFSET_BITS=64  -fPIC -fno-strict-aliasing -g -g -O2 -O2 -g -Wall -Wno-parentheses  -fPIC  -o clamav.o -c clamav.c
clamav.c: In function âclamavr_newâ:
clamav.c:28: warning: unused variable âv_fnameâ
clamav.c: In function âclamavr_setstringâ:
clamav.c:116: error: âstruct RStringâ has no member named âptrâ
clamav.c: In function âclamavr_scanfileâ:
clamav.c:166: error: âstruct RStringâ has no member named âptrâ
make: **\* [clamav.o] Error 1

**Comment by eagleas** [comment]
Version 0.3.2 released

**Comment by dsnezhkov** [comment]
Thank you. I accidentally saw the second comment first. Fixed.
